version: '3'
services:
    app:
        container_name: 'investing-go'
        build: ./scripts
        volumes: 
            - ./scripts:/home/investing-go/scripts
            - ./dados:/home/investing-go/dados
            - ./tests:/home/investing-go/tests
        working_dir: /home/investing-go/scripts
        tty: true