version: '3'
services:
    app:
        container_name: 'investing-go'
        build: ./scripts
        volumes: 
            - ./scripts:/investing-go/scripts
            - ./dados:/investing-go/dados
            - ./tests:/investing-go/tests
        working_dir: /investing-go
        tty: true